service: skills-matrix-backend

plugins:
  - serverless-offline

custom:
  tableThroughputs:
    prod: 5
    default: 1
  tableThroughput: ${self:custom.tableThroughputs.${self:provider.stage}, self:custom.tableThroughputs.default}

provider:
  name: aws
  runtime: nodejs10.x
  versionFunctions: false
  memorySize: 128
  region: us-east-1
  logRetentionInDays: 30
  stage: ${opt:stage, 'dev'}
  environment:
    TABLENAME: ${opt:stage, self:provider.stage}-SkillsTable
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - dynamodb:Scan
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        Fn::GetAtt:
          - SkillsTable
          - Arn

functions:
  skillsList:
    handler: lambda/skillsList.skillsList
    name: ${self:provider.stage}-skillsList
    description: 'CRUD function for skills in the table, ${self:provider.environment.TABLENAME}'
    events:
      - http:
          path: /skillslist
          method: get
          cors: true
      - http:
          path: /skillslist
          method: post
          cors: true
      - http:
          path: /skillslist/{skillId}
          method: patch
          cors: true
      - http:
          path: /skillslist/{skillId}
          method: delete
          cors: true

resources:
  Resources:
    SkillsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.TABLENAME}
        AttributeDefinitions:
          - AttributeName: skillId
            AttributeType: S
        KeySchema:
          - AttributeName: skillId
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: ${self:custom.tableThroughput}
          WriteCapacityUnits: ${self:custom.tableThroughput}

package:
  exclude:
    - mocks/**
  include:
    - ../node_modules/uuid/**
