name: CI workflow

on: [push, pull_request]

jobs:
  build:
    name: lint, test, build, deploy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - name: Use Node.js 10.x
        uses: actions/setup-node@v1
        with:
          version: 10.x

      - name: install yarn
        run: npm install -g yarn

      - run: node --version
      - run: yarn --version

      - run: yarn install

      - run: yarn lint

      - name: yarn test
        env:
          CI: true
        run: yarn test --coverage

      - run: yarn build

      - name: 'PROD: deploy to netlify'
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        run: |
          npm install netlify-cli -g
          netlify deploy --prod
